### ISSUE TITLE
Make cells themselves aware of celltype

### ISSUE THREAD

**Issue by ialokim** [tilk/digitaljs#1]
When instantiating a new gate using [`getCellType`](https://github.com/tilk/digitaljs/blob/master/src/circuit.js#L10) and adding it to the circuit, this newly added gate does not contain a value for `attributes.celltype` as gates loaded from some yosys2digitaljs created json would do. Therefore while saving the circuit into json, these newly added gates do not contain the `celltype` information at all.

One possible workaround is to always pass the celltype manually as an argument to the constructor while creating the gate, but I think it would make more sense if the celltype would be a default attribute for each gate.
Did you have any reason why you've named the celltypes e.g. `$not` in the json files and `Not` when you defined the gates? I've noticed the former is always correctly set into the `type` parameter even on newly added gates (presumably automatically by jointjs?), but it's value is not considered while saving to json.

If not, I would suggest to keep one common name for the gate's definition and inside the json file (if yosys outputs the types as `$not` they could be properly renamed already in yosys2digitaljs I guess) so that additionally added gates would automatically "know" their type.
An alternative solution would be to set the celltype argument as a default for each new Gate definition (probably even overwriting some given value) as the celltype should only depend on the instantiated gate.

**Comment by tilk** [comment]
DigitalJS was designed for working with Yosys outputs first. As such, the simplest possible approach was taken: the gate type identifier was taken as what Yosys outputs, e.g. `$not`. I postponed the issues related to manually creating gates until this is needed.
I agree with you that the simplest solution to your problem is to identify the gates by the class name, and letting JointJS handle the issue. For that, as you say, yosys2digitaljs needs to emit different JSON. As my instance of digitaljs_online has some circuits saved server-side, I wouldn't want to have them stop working, so as a temporary solution DigitalJS should handle both kinds of namings, at least for some transition period.
Are you willing to work on the issue? I don't have time for that currently, and I'd happily accept a pull request which meets the requirements.
