### ISSUE TITLE
Reason why ports are not recognized by jointJS?

### ISSUE THREAD

**Issue by ialokim** [tilk/digitaljs#13]
For some reason, the `ports` object of each gate, e.g.​
```js
{
    "ports": {
        "in1": { "id": "in1", "dir": "in", "bits": 3 },
        "in2": { "id": "in2", "dir": "in", "bits": 3 },
    ​​    "out": { "id": "out", "dir": "out", "bits": 3 }
    }
}
```

for a simple `Or` gate is not recognized by the native jointJS functions such as [`getPorts()`](https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#dia.Element.prototype.getPorts). Was there any reason why you didn't use the native jointJS functions to add ports (even [with own, separated markup](https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#dia.Element.ports))? I think it would have made some things clearer and easier to use if you'd stick to the jointJS API.

**Comment by ialokim** [comment]
It seems ports added via `addPort()` are stored inside `model.attributes.ports.items`.

**Comment by tilk** [comment]
I can't remember why it is designed the way it is. Maybe there was some problem in jointJS with that API at the time; a lot has changed for the better in jointJS since I started developing DigitalJS. If you can prepare a redesign which uses this API, is nice and elegant, and does not break things, I can merge that.
